cleaning of previous output-dir: save latest as a tar file

diff --git a/tools/example_scripts/ACESgrid/aces_test_adm_mpi b/tools/example_scripts/ACESgrid/aces_test_adm_mpi
--- a/tools/example_scripts/ACESgrid/aces_test_adm_mpi
+++ b/tools/example_scripts/ACESgrid/aces_test_adm_mpi
@@ -57,7 +57,21 @@ if [ $dsp -le 1000000 ] ; then
 fi
 if [ $checkOut -eq 1 ] ; then
   if test -d $gcmDIR/CVS ; then
-    /bin/rm -rf $gcmDIR/verification/??_${dNam}-${sfx}_????????_?
+#- remove previous output tar files and tar & remove previous output-dir
+    /bin/rm -f $gcmDIR/verification/??_${dNam}-${sfx}_????????_?.tar.gz
+    ( cd $gcmDIR/verification
+      listD=`ls -1 -d ??_${dNam}-${sfx}_????????_?`
+      for dd in $listD
+      do
+        if test -d $dd ; then
+          tar -cf ${dd}".tar" $dd > /dev/null 2>&1 && gzip ${dd}".tar" && /bin/rm -rf $dd
+          RETVAL=$?
+          if test "x$RETVAL" != x0 ; then
+             echo "ERROR in tar+gzip prev outp-dir: $dd"
+             echo " on '"`hostname`"' (return val=$RETVAL) but continue"
+          fi
+        fi
+      done )
 #   ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
     echo "cvs update of dir $gcmDIR :"
     ( cd $gcmDIR ; cvs -q -d :pserver:cvsanon@mitgcm.org:/u/gcmpack update -P -d ) 2>&1
