o make "ln -s" handling smarter and remove it from the options files

diff --git a/tools/genmake2 b/tools/genmake2
--- a/tools/genmake2
+++ b/tools/genmake2
@@ -704,8 +704,8 @@ if test "x${AD_OPTFILE}" != xNONE ; then
     fi
 fi
 
-#  Check that FC, LINK, CPP, and S64 are defined.  If not, complain 
-#  and abort!
+#  Check that FC, LINK, CPP, S64, and LN are defined.  If not,
+#  complain and abort!
 if test "x$FC" = x ; then
     cat <<EOF 1>&2
 
@@ -741,7 +741,22 @@ fi
 if test "x$MAKEDEPEND" = x ; then
     MAKEDEPEND=makedepend
 fi
+if test "x$LN" = x ; then
+    LN="ln -s"
+fi
+echo "test" > genmake_test_ln
+$LN genmake_test_ln genmake_tlink
+RETVAL=$?
+if test "x$RETVAL" != x0 ; then
+    cat <<EOF 1>&2
 
+Error: The command "ln -s" failed -- please specify a working soft-link
+  command in the optfile.
+
+EOF
+    exit 1
+fi
+rm -f genmake_test_ln genmake_tlink
 
 printf "\n===  Checking system libraries  ===\n"
 echo -n "  Do we have the system() command using $FC...  "
