Added backup selection of xmakedepend in TOOLSDIR for occasions when makedepend does not exist on the system (e.g. new and partial Linux installs).

diff --git a/tools/genmake2 b/tools/genmake2
--- a/tools/genmake2
+++ b/tools/genmake2
@@ -104,6 +104,16 @@ find_possible_configs()  {
 	CPP="cpp -traditional -P"
     fi
 
+    # makedepend is not always available
+    if test "x${MAKEDEPEND}" = x ; then
+      which makedepend >& /dev/null
+      RETVAL=$?
+      if test "x${RETVAL}" = x1 ; then
+         echo "    makedepend was not found. Using xmakedpend instead."
+         MAKEDEPEND='$(TOOLSDIR)/xmakedepend'
+      fi
+    fi
+
     # look for possible fortran compilers
     tmp="$MITGCM_FC $FC efc g77 f77 pgf77 pgf95 ifc f90 f95 mpif77 mpf77 mpxlf95"
     p_FC=
