add warning about inappropriate user masks and/or file permissions that   will cause the file dependency code to break (I think this fixes the   problem reported by S. Vinogradov -- will need testing) :   http://forge.csail.mit.edu/pipermail/mitgcm-support/2006-February/003781.html

diff --git a/tools/genmake2 b/tools/genmake2
--- a/tools/genmake2
+++ b/tools/genmake2
@@ -2151,6 +2151,24 @@ fi
 echo "  Determining the list of source and include files"
 rm -rf .links.tmp
 mkdir .links.tmp
+touch .links.tmp/foo
+if test ! -r ".links.tmp/foo" ; then
+    echo
+    echo "ERROR : something is wrong with your directory permissions or"
+    echo "   your user file-creation mask (\"umask\") since creating a"
+    echo "   sub-dir, touch-ing a file within it, and then reading it is"
+    echo "   not working.  Please try setting your umask to something"
+    echo "   sane such as:"
+    echo
+    echo "      umask 0002"
+    echo
+    echo "   and please verify that you have the proper permissions for"
+    echo "   creating sub-directories and then reading files created"
+    echo "   within them."
+    echo
+    exit 1
+fi
+rm -f .links.tmp/foo
 echo "# This section creates symbolic links" > srclinks.tmp
 echo "" >> srclinks.tmp
 printf 'SRCFILES = '    > srclist.inc
